
### OTTENERE TUTTI I BLOGPOST
GET http://localhost:5000/blogposts

### OTTENERE SOLO UN POST
GET http://localhost:5000/blogposts/{postId}


### OTTENERE I POST DI UN AUTORE
GET http://localhost:5000/authors/{authorId}/blogposts


### CREARE UN POST NUOVO
POST http://localhost:5000/blogposts
Content-Type: application/json

{
  "category": "Tech",
  "title": "Nuovo Post su Tecnologia",
  "cover": "https://picsum.photos/200/200",
  "readTime": {
    "value": 5,
    "unit": "min"
  },
  "author": "{authorId}",  // ID dell'autore
  "content": "Questo è il contenuto del post."
}


### AGGIORNARE UN POST

PUT http://localhost:5000/blogposts/{postId}
Content-Type: application/json

{
  "category": "Tech",
  "title": "Post Aggiornato su Tecnologia",
  "cover": "https://picsum.photos/300/300",
  "readTime": {
    "value": 10,
    "unit": "min"
  },
  "author": "{authorId}",  // ID dell'autore
  "content": "Questo è il contenuto aggiornato del post."
}



### CANCELLARE UN POST

DELETE http://localhost:5000/blogposts/{postId}


###
# Richiesta per cancellare tutti i blog posts
DELETE http://localhost:5000/blogposts
