GET http://localhost:5000/blogposts

###

GET http://localhost:5000/blogposts/66c6c25572d50b71605be95e

###

GET http://localhost:5000/blogposts/66c6d85bd1cb5222f22b4ae6

###

POST http://localhost:5000/blogposts
Content-Type: application/json

{
  "category": "Tech",
  "title": "New Post",
  "cover": "http://example.com/image.jpg",
  "readTime": {
    "value": 5,
    "unit": "minutes"
  },
  "author": "author@example.com",
  "content": "This is the content of the post."
}


###

POST http://localhost:5000/blogposts
Content-Type: application/json

{
  "category": "Science",
  "title": "Science Post",
  "cover": "http://example.com/image.jpg",
  "readTime": {
    "value": 7,
    "unit": "minutes"
  },
  "author": "author2@example.com",
  "content": "This is the content of the science post."
}

###

PUT http://localhost:5000/blogposts/66c6c25572d50b71605be95e
Content-Type: application/json

{
  "category": "Tech",
  "title": "New Post",
  "cover": "https://picsum.photos/1200/630",
  "readTime": {
    "value": 5,
    "unit": "minutes"
  },
  "author": "author@example.com",
  "content": "This is the content of the post."
}

###

PUT http://localhost:5000/blogposts/66c6d85bd1cb5222f22b4ae6
Content-Type: application/json

{
  "category": "Science",
  "title": "Science Post",
  "cover": "https://picsum.photos/1200/630",
  "readTime": {
    "value": 7,
    "unit": "minutes"
  },
  "author": "author2@example.com",
  "content": "This is the content of the science post."
}

###

DELETE http://localhost:5000/blogposts/66c629b9e85014bb759dcf19


###
# Richiesta per cancellare tutti i blog posts
DELETE http://localhost:5000/blogposts
