### Registrazione nuovo usuario
POST http://localhost:5000/register
Content-Type: application/json

{
    "username": "Sara Casotto",
    "email": "sara@casotto.com",
    "password": "password123"
}


### Login usuario esistente
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "sara@casotto.com",
    "password": "password123"
}

### 
GET http://localhost:5000/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmQ1ZTYzYWFhNWU3Yjk2NGI1ZTY1NjMiLCJpYXQiOjE3MjUyOTUxMTMsImV4cCI6MTcyNTI5ODcxM30.r3E8XIPl6KQsFH9ZQP7v7xLe4cylDpceEbe2LbBRums

